name: ocx24-dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.11
  - flask=3.1.2
  - jupyter
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - plotly
  - pillow
  - pip
  - pip:
      - attrs==25.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastjsonschema==2.21.2
      - fonttools==4.59.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - narwhals==2.2.0
      - nbformat==5.10.4
      - pyparsing==3.2.3
      - pytz==2025.2
      - referencing==0.36.2
      - rpds-py==0.27.1
      - threadpoolctl==3.6.0
      - tzdata==2025.2

